//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class HigherEducationChesterfieldCollegeEntities : DbContext
{
    public HigherEducationChesterfieldCollegeEntities()
        : base("name=HigherEducationChesterfieldCollegeEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Comment> Comments { get; set; }
    public virtual DbSet<Course> Courses { get; set; }
    public virtual DbSet<Image> Images { get; set; }
    public virtual DbSet<SubjectArea> SubjectAreas { get; set; }
    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    public virtual DbSet<AdminLogin> AdminLogins { get; set; }
    public virtual DbSet<FavouriteCourse> FavouriteCourses { get; set; }
    public virtual DbSet<UserLogin> UserLogins { get; set; }
}
