//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class AdminLogin
{
    public int ID { get; set; }
    public string FirstName { get; set; }
    public string Surname { get; set; }
    public string DateOfBirth { get; set; }
    public string Gender { get; set; }
    public string EmailAddress { get; set; }
    public string Password { get; set; }
    public bool LoggedOn { get; set; }
}

public partial class Comment
{
    public int ID { get; set; }
    public string EmailAddress { get; set; }
    public string CommentInformation { get; set; }
    public System.DateTime DateAndTimeOfCommentSent { get; set; }
    public Nullable<int> CourseID { get; set; }

    public virtual Course Course { get; set; }
}

public partial class Course
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Course()
    {
        this.Comments = new HashSet<Comment>();
        this.FavouriteCourses = new HashSet<FavouriteCourse>();
    }

    public int ID { get; set; }
    public string Name_Course { get; set; }
    public Nullable<int> ImageID { get; set; }
    public string AdditionalInformation { get; set; }
    public string PartFullTime { get; set; }
    public int LevelOfCourse { get; set; }
    public int SubjectAreaID { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Comment> Comments { get; set; }
    public virtual Image Image { get; set; }
    public virtual SubjectArea SubjectArea { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<FavouriteCourse> FavouriteCourses { get; set; }
}

public partial class FavouriteCourse
{
    public int ID { get; set; }
    public Nullable<int> userLoginID { get; set; }
    public Nullable<int> CourseID { get; set; }

    public virtual Course Course { get; set; }
    public virtual UserLogin UserLogin { get; set; }
}

public partial class Image
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Image()
    {
        this.Courses = new HashSet<Course>();
        this.SubjectAreas = new HashSet<SubjectArea>();
    }

    public int ID { get; set; }
    public string Name { get; set; }
    public string ContentType { get; set; }
    public byte[] Data { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Course> Courses { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SubjectArea> SubjectAreas { get; set; }
}

public partial class SubjectArea
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SubjectArea()
    {
        this.Courses = new HashSet<Course>();
    }

    public int ID { get; set; }
    public string Name_SA { get; set; }
    public Nullable<int> ImageID { get; set; }
    public string AdditionalInformation { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Course> Courses { get; set; }
    public virtual Image Image { get; set; }
}

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class UserLogin
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public UserLogin()
    {
        this.FavouriteCourses = new HashSet<FavouriteCourse>();
    }

    public int ID { get; set; }
    public string FirstName { get; set; }
    public string Surname { get; set; }
    public string DateOfBirth { get; set; }
    public string Gender { get; set; }
    public string EmailAddress { get; set; }
    public string PhoneNumber { get; set; }
    public string CurrentStudent { get; set; }
    public string Password { get; set; }
    public bool LoggedOn { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<FavouriteCourse> FavouriteCourses { get; set; }
}
